name: Build

on:
  push:
    tags: release/batch/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Get version
      id: version
      run: |
        version=echo ${{ github.ref }} | 's/refs.*\///g'
        echo "::set-output name=versin::$version"
    - run: echo ${{ steps.version.outputs.version }}
