name: Build

on:
  push:
    tags: release/batch/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Get version form refs
      id: version
      run: |
        version=$(echo ${{ github.ref }} | sed 's/refs.*\///g')
        echo "::set-output name=version::$version"
    - run: echo ${{ steps.version.outputs.version }}
    - name: delete command tag
      run: |
       git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
       git push --delete origin ${{ github.ref }}
