name: Release
on:
  pull_request_review:
    types: [ submitted ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA
      - run: echo $GITHUB_REF
      - run: |
          mkdir -p artifact
          cp $GITHUB_EVENT_PATH artifact/event.json
          
      - uses: actions/upload-artifact@v1
        with:
          name: json
          path: artifact
      - uses: taichi/approved-event-action@master
        id: approved
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Approved !!"
        if: steps.approved.outputs.approved == 'true'
    
