name: Release
on:
  pull_request_review:
    types: [ submitted ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA
      - run: echo $GITHUB_REF
      - run: |
          mkdir -p artifact
          echo "${{ toJSON(github.event) }}" > artifact/event.json
      - uses: actions/upload-artifact@v1
        with:
          name: event.json
          path: artifact
          
    
